language: node_js
node_js:
  - "node"

cache: npm

env:
  global:
    secure: hash value

script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
